### ISSUE TITLE
room.memberAll();不带参数不能返回所有成员信息

### ISSUE THREAD

**Issue by renwfy** [botorange/wechaty-puppet-padpro#104]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.19.137
- wechaty-puppet-padpro 版本：0.0.50
- node 版本： v10.15.3
- 你使用的操作系统：mac

## 2. Bug 描述
room.memberAll();不带参数不能返回所有成员信息

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
- 第一步：
- 第二步：
- 。。。

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
Error: no query
    at PuppetPadpro.<anonymous> (/Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/node_modules/_wechaty-puppet@0.14.1@wechaty-puppet/dist/src/puppet.js:560:23)
    at Generator.next (<anonymous>)
    at /Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/node_modules/_wechaty-puppet@0.14.1@wechaty-puppet/dist/src/puppet.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/node_modules/_wechaty-puppet@0.14.1@wechaty-puppet/dist/src/puppet.js:21:12)
    at PuppetPadpro.roomMemberSearch (/Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/node_modules/_wechaty-puppet@0.14.1@wechaty-puppet/dist/src/puppet.js:554:16)
    at AnotherOriginalClass.<anonymous> (/Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/node_modules/_wechaty@0.19.162@wechaty/dist/src/user/room.js:756:53)
    at Generator.next (<anonymous>)
    at /Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/node_modules/_wechaty@0.19.162@wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/node_modules/_wechaty@0.19.162@wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.memberAll (/Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/node_modules/_wechaty@0.19.162@wechaty/dist/src/user/room.js:754:16)
    at members (/Users/LSD/Documents/WorkSpace/Nodejs/SmartheadX-Services/routes/api-controller/group.js:58:38)

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by renwfy** [comment]
"wechaty": "^0.22.1",  可以成功
