### ISSUE TITLE
centos 安装 wechaty-puppet-padpro卡在gRPC module

### ISSUE THREAD

**Issue by handsomejustin** [botorange/wechaty-puppet-padpro#106]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.22.6
- wechaty-puppet-padpro 版本：0.0.57
- node 版本： (运行 `node --version` 获取版本)： v10.15.3
- 你使用的操作系统：CentOS release 6.10 (Final)

## 2. Bug 描述
请用精简的语言描述你遇到的bug
执行到安装wechaty-puppet-padpro后，执行node index.js会出现：
Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
- 第一步： node index.js

[root@ecs-85 wechaty-puppet-padpro]# node index.js
Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/src/grpc_extension.js:43:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/src/client.js:35:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/index.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/gateway/grpc-gateway.js:14:32)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/gateway/wechat-gateway.js:21:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/manager/padpro-grpc.js:14:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:16:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/puppet-padpro.js:40:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/index.js:21:25)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/index.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[root@ecs-85 wechaty-puppet-padpro]# cd node_modules/

- 第二步：npm rebuild

[root@ecs-85 wechaty-puppet-padpro]# npm rebuild

> fast-xml-parser@3.12.16 postinstall /home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

> nosql-leveldb@3.0.1 install /home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/node_modules/flash-store/node_modules/nosql-leveldb
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=linux)
make: Entering directory `/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
cc1plus: error: unrecognized command line option "-std=gnu++1y"
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o] Error 1
make: Leaving directory `/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 2.6.32-754.11.1.el6.x86_64
gyp ERR! command "/usr/local/node/node-v10.15.3-linux-x64/bin/node" "/usr/local/node/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/justin/wechaty/wechaty-puppet-padpro/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nosql-leveldb@3.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nosql-leveldb@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justin/.npm/_logs/2019-04-22T10_12_40_803Z-debug.log
[root@ecs-85 wechaty-puppet-padpro]#

- 。。。

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果
在CentOS下配置成功（本人在windows10上已经顺利运行了，但是在centOS上无论如何无法配置成功）

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
[root@ecs-85 wechaty-puppet-padpro]# node index.js
Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/src/grpc_extension.js:43:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/src/client.js:35:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_grpc@1.20.0@grpc/index.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/gateway/grpc-gateway.js:14:32)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/gateway/wechat-gateway.js:21:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/manager/padpro-grpc.js:14:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:16:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/puppet-padpro.js:40:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/dist/src/index.js:21:25)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/justin/wechaty/wechaty-puppet-padpro/index.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)


[root@ecs-85 wechaty-puppet-padpro]# npm rebuild

> fast-xml-parser@3.12.16 postinstall /home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0


> nosql-leveldb@3.0.1 install /home/justin/wechaty/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.57@wechaty-puppet-padpro/node_modules/flash-store/node_modules/nosql-leveldb
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=linux)
make: Entering directory `/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
cc1plus: error: unrecognized command line option "-std=gnu++1y"
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o] Error 1
make: Leaving directory `/home/justin/wechaty/wechaty-puppet-padpro/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 2.6.32-754.11.1.el6.x86_64
gyp ERR! command "/usr/local/node/node-v10.15.3-linux-x64/bin/node" "/usr/local/node/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/justin/wechaty/wechaty-puppet-padpro/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nosql-leveldb@3.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nosql-leveldb@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justin/.npm/_logs/2019-04-22T10_12_40_803Z-debug.log

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
我无法复现你的问题，我成功安装了 wechaty-puppet-padpro在centos 6.10上面

![image](https://user-images.githubusercontent.com/6801292/57467037-5ce98b80-72b4-11e9-8fc6-c4f5282fb277.png)

我参考了这个文章安装nodejs
https://linuxize.com/post/how-to-install-node-js-on-centos-7/

然后使用安装gcc依赖
```
yum groupinstall 'Development Tools'
```

之后遇到一个报错，用下面这个文章解决
https://blog.csdn.net/qq_26744901/article/details/82504079

这个issue就关闭了，无法安装成功和wechaty-puppet-padpro无关，请自行解决
