### ISSUE TITLE
发送.doc .docx文档失败，其他文件正常

### ISSUE THREAD

**Issue by sifanlook** [botorange/wechaty-puppet-padpro#131]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：^0.26.1
- wechaty-puppet-padpro 版本：^0.2.1
- node 版本： v10.15.3
- 你使用的操作系统：windows

## 2. Bug 描述
发送.doc .docx文档失败，其他文件正常。
我把一个txt文件后缀名改成doc或docx又是可以发送的，自己新建一个doc文件发送就报错。

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
发送文件代码：
` var fileBox = file_box_1.FileBox.fromUrl('http://94.191.***:8080/images/aaa.docx','退服数量'.docx');
await room.say(fileBox);`
## 4. 期待程序运行的结果
文件发送成功

## 5. 程序实际运行的结果
doc文件发送失败

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

{ Error: Parse Error
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }
{ Error: Parse Error
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }
{ Error: Parse Error
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }
{ Error: Parse Error
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }
12:26:50 INFO PadproManager initData() finished with contacts: 978, rooms: 11

```

</details>

## 7. 其他信息
文件名不可为中文
![image](https://user-images.githubusercontent.com/21136881/58147444-140add00-7c8d-11e9-909c-a1eb6070499c.png)

[bug]

**Comment by sifanlook** [comment]
（补充）
2019/05/22 16:48
我又测了一下，发现了问题所在：
**var fileBox = file_box_1.FileBox.fromUrl('http://94.191.***:8080/images/aaa.docx','退服数量'.docx'); await room.say(fileBox);**
1. FileBox.fromUrl（）方法的两个文件名都设置成英文，任何文件都可以发送。
2. 出现上面的问题是因为第二个参数设置成了中文，直接报错。
3. 还发现一个问题：
   **第一次发送  FileBox.fromUrl('http://94.191.***:8080/images/aaa.docx','aaa.docx');  成功
   第二次发送  FileBox.fromUrl('http://94.191.***:8080/images/aaa.docx','退服数量.docx'); 也会成功
   若第一次直接发送 FileBox.fromUrl('http://94.191.***:8080/images/aaa.docx','退服数量.docx');   会失败**
总结：当aaa.docx文件已经上送到服务器，假设aaa.docx在服务器没有变动，此时第二个文件传中文正常。但是实际生产环境中aaa.docx是不断变动的，希望这个问题得到解决。

**Comment by windmemory** [comment]
@sifanlook 非常感谢详细的测试以及问题的定位，这个问题我们尽快处理。

**Comment by windmemory** [comment]
@sifanlook 非常感谢你的反馈，我们刚刚发布了`v0.3.5`，解决了发送中文名文件的问题，请更新版本再次测试看看。

**Comment by sifanlook** [comment]
升级 0.3.5 版本后，问题解决。
