### ISSUE TITLE
Warning: flash-store@0.7 will not be able to install at Ubuntu 19 by default

### ISSUE THREAD

**Issue by huan** [botorange/wechaty-puppet-padpro#138]
That's because the Python 2 had been deprecated from Ubuntu 19.

Use `flash-store@0.14` will work without any problem.

The following log is copy/pasted from a Ubuntu 19.04 box:

```shell
┌ huan@huan-home:~/git/matrix-appservice-wechaty [00:56:48] tty:[1] jobs:[0]
└ {master} $ npm i flash-store@latest
+ flash-store@0.14.1
removed 245 packages, updated 1 package and audited 1428 packages in 21.542s
found 0 vulnerabilities

┌ huan@huan-home:~/git/matrix-appservice-wechaty [00:57:13] tty:[1] jobs:[0]
└ {master} $ npm i flash-store@0.7

> nosql-leveldb@3.0.1 install /home/huan/git/matrix-appservice-wechaty/node_modules/nosql-leveldb
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.2 runtime=node arch=x64 platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Linux 5.0.0-15-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/huan/git/matrix-appservice-wechaty/node_modules/nosql-leveldb
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nosql-leveldb@3.0.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nosql-leveldb@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/huan/.npm/_logs/2019-06-12T16_57_56_563Z-debug.log
```

**Comment by huan** [comment]
Close this issue because #137 had been merged.
