### ISSUE TITLE
toFileBox 一直失败

### ISSUE THREAD

**Issue by xpurer** [botorange/wechaty-puppet-padpro#165]
# 1. 提供你的包版本信息
使用的版本
    "wechaty": "^0.26.1",
    "wechaty-puppet-padpro": "^0.2.1"

- node 版本： (运行 `node --version` 获取版本) 11.6.0
- 你使用的操作系统： centos7

## 2. Bug 描述

toFileBox 一直失败

Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (internal/crypto/cipher.js:173:29)
    at Object.exports.decryptAes (/root/wxbot/node_modules/wechaty-puppet-padpro/dist/src/utils/aes-utils.js:18:41)
    at CDNManager.<anonymous> (/root/wxbot/node_modules/wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:159:28)
    at Generator.next (<anonymous>:null:null)
    at /root/wxbot/node_modules/wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:7:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/root/wxbot/node_modules/wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:3:12)
    at CDNManager.downloadFile (/root/wxbot/node_modules/wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:130:16)
    at PuppetPadpro.<anonymous> (/root/wxbot/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:706:56)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/root/wxbot/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by xpurer** [comment]
升级到0.3.8之后解决了

**Comment by xpurer** [comment]
更新到
    "wechaty": "^0.27.53",
    "wechaty-puppet-padpro": "^0.3.8"
 依然报错

**Comment by su-chang** [comment]
有复现详细的步骤么？我这边帮你看一下

**Comment by windmemory** [comment]
Please try with `v0.3.11` and see if the issue still happens.
