### ISSUE TITLE
Package version need when moving from PadChat to PadPro

### ISSUE THREAD

**Issue by idisblueflash** [botorange/wechaty-puppet-padpro#26]
Could anyone help me to make sure I'm using the right version when moving?

We were using PadChat before, and it works nice with `package.json`:
```JSON
  "dependencies": {
    "@types/es6-promise": "^3.3.0",
    "@types/lru-cache": "^4.1.1",
    "@types/node": "^10.12.0",
    "@types/raven": "^2.5.1",
    "axios": "^0.18.0",
    "file-box": "^0.8.23",
    "http": "0.0.0",
    "qrcode-terminal": "^0.12.0",
    "raven": "^2.6.4",
    "redis": "^2.8.0",
    "ts-node": "^7.0.1",
    "typescript": "^3.1.3",
    "wechaty": "^0.22.4",
    "wechaty-puppet": "^0.14.1",
    "wechaty-puppet-padchat": "^0.16.2"
  },
```

When we try to move this to PadPro, removing `wechaty-puppet-padchat` package and use `wechaty-puppet-padpro` instead, like below:
```JSON
  "dependencies": {
    ...
    "wechaty": "^0.22.4",
    "wechaty-puppet": "^0.14.1",
    "wechaty-puppet-padpro": "0.0.26"
  },
```

We've got problem:
```bash
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb cwd /wechat-bot
npm verb Linux 4.9.125-linuxkit
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v10.11.0
npm verb npm  v6.4.1
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/zixia/levelup.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
npm verb exit [ 1, true ]
npm timing npm Completed in 11367ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-21T07_54_59_225Z-debug.log
ERROR: Service 'bot' failed to build: The command '/bin/sh -c cd /wechat-bot/  && npm install --verbose  && npm dedupe --verbose  && npm ls --verbose  && npm cache clean --force' returned a non-zero code: 1
```

I guess we need set some correct version for `wechaty` and `wechaty-puppet` as well?

**Comment by windmemory** [comment]
Hi,

`wechaty-puppet-padpro` is using the latest `wechaty` and `wechaty-puppet`, so please use version below:

```json
{
  "wechaty":"^0.23.30",
  "wechaty-puppet":"^0.15.1"
}
```

**Comment by idisblueflash** [comment]
Thank you.

After we changed with new version, and added `git` command in our dockerfile, we met new errors:

```
  +-- socks5-http-client@1.0.4
  | `-- socks5-client@1.2.6 deduped
  +-- wechaty-puppet@0.15.7 deduped
  `-- xml2js@0.4.19
    +-- sax@1.2.1
    `-- xmlbuilder@9.0.7

npm ERR! extraneous: regenerator-runtime@0.12.1 /wechat-bot/node_modules/wechaty-puppet-padpro/node_modules/regenerator-runtime
npm ERR! missing: regenerator-runtime@^0.12.0, required by @babel/runtime@7.1.5
npm ERR! missing: levelup@github:zixia/levelup, required by flash-store@0.7.1
npm verb exit [ 1, true ]
npm timing npm Completed in 3356ms
npm verb code 1
ERROR: Service 'bot' failed to build: The command '/bin/sh -c cd /wechat-bot/  && npm install --verbose  && npm dedupe --verbose  && npm ls --verbose  && npm cache clean --force  && apt-get clean  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

Could you help to point out what we've done wrong?

**Comment by windmemory** [comment]
This is hard to debug from the log provided. What is the root cause for the error? Can you split the command into separate ones then see which one fails? With the long command 
```shell
/bin/sh -c cd /wechat-bot/  && npm install --verbose  && npm dedupe --verbose  && npm ls --verbose  && npm cache clean --force  && apt-get clean  && rm -rf /var/lib/apt/lists/*
```

I don't know where to start looking at.

**Comment by idisblueflash** [comment]
It's a good idea to do a separate test! Thank you.

**Comment by idisblueflash** [comment]
Did I install a wrong version of puppeteer?
Since it stopped at installing puppeteer@1.10.0.

I separate install step, and found error below:
```
npm WARN t3wechat@0.1.0 No license field.

npm verb stack Error: puppeteer@1.10.0 install: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:182:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:962:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm verb pkgid puppeteer@1.10.0
npm verb cwd /wechat-bot
npm verb Linux 4.9.125-linuxkit
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v10.11.0
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.10.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 72034ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-22T03_13_36_459Z-debug.log
ERROR: Service 'bot' failed to build: The command '/bin/sh -c cd /wechat-bot/  && npm install --verbose' returned a non-zero code: 1
```

I'm using macOS 10.14.2, and node 11.10.0.

**Comment by windmemory** [comment]
Please try node 10. Remove `node_modules` and `package-lock.json`, then do a install.

**Comment by idisblueflash** [comment]
Sorry for typo, I'm using Node 10.11.0

**Comment by windmemory** [comment]
Remove node_modules and package-lock.json, then do a install.

**Comment by windmemory** [comment]
@idisblueflash Do you still have issues starting `wechaty` with `wechaty-puppet-padpro`? If not, I will close this issue.

**Comment by idisblueflash** [comment]
Thank you. I can run it.

need install another package: "regenerator-runtime": "^0.12.0"

**Comment by idisblueflash** [comment]
Thank you. I can run it.

need install another package: "regenerator-runtime": "^0.12.0"

**Comment by jubel-han** [comment]
@windmemory Here is the root cause

![image](https://user-images.githubusercontent.com/7992512/50876322-72829d80-1407-11e9-839b-b9ce21747795.png)
```
npm ERR! missing: levelup@github:zixia/levelup, required by flash-store@0.7.1
```

**The nested dependencies are missing:** (with the above `package.json`)

`wechaty-puppet-padpro@0.0.26` requires the `flash-store@0.7.1`

`flash-store@0.7.1` requires the `levelup@github:zixia/levelup`

 however the `levelup` is missing.

**Comment by idisblueflash** [comment]
@windmemory I assume we don't need to reinstall PadPro again, do we?

Since it install an old PadPro(wechaty-puppet-padpro@0.0.1) when I run demo.js first time.

```bash
➜  wechat-bot git:(feature/wechat-bot-upgrade) ✗ node demo.js
12:39:25 INFO Wechaty <wechaty-puppet-padpro> start() v0.23.30 is starting...
12:39:25 INFO PuppetManager install(wechaty-puppet-padpro@^0.0.1) please wait ...
npm: 
> nosql-leveldb@3.0.1 install /Users/top20/Offices/wechat-bot/node_modules/wechaty/node_modules/nosql-leveldb
> prebuild-install || node-gyp rebuild


npm: prebuild-install
npm:  WARN install No prebuilt binaries found (target=8.4.0 runtime=node arch=x64 platform=darwin)

npm: gyp
npm:  WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

npm: gyp 
npm: WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

npm: gyp WARN
npm:  download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o

npm:   CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o

npm:   LIBTOOL-STATIC Release/leveldb.a

npm:   CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o

npm:   CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-stubs-internal.o

npm:   CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o

npm:   LIBTOOL-STATIC Release/snappy.a

npm:   CXX(target) Release/obj.target/leveldown/src/batch.o

npm:   CXX(target) Release/obj.target/leveldown/src/database.o

npm:   CXX(target) Release/obj.target/leveldown/src/iterator.o

npm:   CXX(target) Release/obj.target/leveldown/src/leveldown.o

npm:   SOLINK_MODULE(target) Release/leveldown.node

npm: 
> grpc@1.17.0 install /Users/top20/Offices/wechat-bot/node_modules/wechaty/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library


npm: node-pre-gyp
npm:  
npm: WARN Using request for node-pre-gyp https download 

npm: [grpc] Success: "/Users/top20/Offices/wechat-bot/node_modules/wechaty/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node" is installed via remote

npm: 
> fast-xml-parser@3.12.11 postinstall /Users/top20/Offices/wechat-bot/node_modules/wechaty/node_modules/fast-xml-parser
> node tasks/postinstall.js


npm:               Donating to an open source project is more affordable

npm: 

npm:                   *** Thank you for using fast-xml-parser! ***

                 Please consider donating to help us maintain this package.


npm:    https://opencollective.com/fast-xml-parser/donate
                                      or
  https://www.patreon.com/bePatron?u=9531404
                                      or
  https://www.paypal.me/amitkumarguptagwl

npm: 



npm: npm notice
npm:  created a lockfile as package-lock.json. You should commit this file.

npm: npm WARN
npm:  wechaty-puppet-padpro@0.0.1 requires a peer of file-box@^0.8.23 but none was installed.
npm WARN wechaty-puppet-padpro@0.0.1 requires a peer of wechaty-puppet@^0.14.1 but none was installed.
npm 
npm: WARN rx-queue@0.4.30 requires a peer of brolog@^1.4.9 but none was installed.

npm: 

npm: + wechaty-puppet-padpro@0.0.1
added 397 packages in 77.272s

12:40:43 INFO PuppetManager install(wechaty-puppet-padpro@^0.0.1) done
12:40:44 INFO WechatGateway start()

```

demo.js
```javescript
"use strict";
exports.__esModule = true;
var wechaty_1 = require("wechaty");
var WECHATY_PUPPET_PADPRO_TOKEN = 'puppet_padpro_token';
var puppet = 'wechaty-puppet-padpro'; // 使用ipad 的方式接入。
var puppetOptions = {
    token: WECHATY_PUPPET_PADPRO_TOKEN
};
var bot = new wechaty_1.Wechaty({
    puppet: puppet,
    puppetOptions: puppetOptions
});
// 设置完成
// 运行 wechaty
bot
    .on('scan', function (qrcode, status) { return console.log("Scan QR Code to login: " + status + "\nhttps://api.qrserver.com/v1/create-qr-code/?data=" + encodeURIComponent(qrcode)); })
    .on('login', function (user) { return console.log("User " + user + " logined"); })
    .on('message', function (message) { return console.log("Message: " + message); })
    .start();

```

**Comment by windmemory** [comment]
@jubel-han what's the root cause for? I don't get it. Could you explain more about the issue you are facing?

**Comment by windmemory** [comment]
@idisblueflash This issue should be caused by some bug in the `puppet-manager` in `wechaty` repository. So you could open an issue there to get some help. 

Here is a workaround that I suggest:
* Create a `PuppetPadpro` instance manually
* Pass the puppet instance to `Wechaty` constructor

Please try this example code:
```javascript
"use strict";
exports.__esModule = true;
var wechaty_1 = require("wechaty");
var padpro = require("wechaty-puppet-padpro");
var WECHATY_PUPPET_PADPRO_TOKEN = 'puppet_padpro_token';
var puppet = new padpro.PuppetPadpro(
    token: WECHATY_PUPPET_PADPRO_TOKEN
)
var bot = new wechaty_1.Wechaty({
    puppet: puppet
});
// 设置完成
// 运行 wechaty
bot
    .on('scan', function (qrcode, status) { return console.log("Scan QR Code to login: " + status + "\nhttps://api.qrserver.com/v1/create-qr-code/?data=" + encodeURIComponent(qrcode)); })
    .on('login', function (user) { return console.log("User " + user + " logined"); })
    .on('message', function (message) { return console.log("Message: " + message); })
    .start();
```
