### ISSUE TITLE
Adding Contact to Room is not working

### ISSUE THREAD

**Issue by lhr0909** [botorange/wechaty-puppet-padpro#30]
Verified that the contact is not in the specified room.

Logs below:

```
15:45:29 VERB Room find() confirm room[#0] with id=5977226699 is vlaid result, return it.
15:45:29 VERB Room add(Contact<H.kt>)
15:45:29 VERB PuppetPadpro roomAdd(5977226699@chatroom, zhao_cq)
15:45:29 VERB PuppetPadpro roomAdd(5977226699@chatroom, zhao_cq) try to Add
15:45:29 SILL PadproGrpc GrpcAddRoomMember(5977226699@chatroom, zhao_cq)
15:45:29 SILL DedupeApi dedupe() no need to dedupe api GrpcAddRoomMember.
15:45:29 SILL WechatGateway sendShort() res: commandUrl: /cgi-bin/micromsg-bin/addchatroommember
15:45:29 SILL GrpcGateway parse(GrpcAddRoomMember) get response: [{"MemberName":"zhao_cq","MemberStatus":4}]
15:45:29 VERB PadproManager roomMemberRawPayloadDirty(5977226699@chatroom)
15:45:29 VERB Puppet roomMemberPayloadDirty(5977226699@chatroom)
15:45:29 VERB PuppetPadpro roomMemberList(5977226699@chatroom)
15:45:29 VERB PadproManager getRoomMemberIdList(5977226699@chatroom)
15:45:29 SILL PadproManager syncRoomMember(5977226699@chatroom)
15:45:29 SILL PadproGrpc GrpcGetChatRoomMember(5977226699@chatroom)
15:45:29 SILL DedupeApi dedupeApi(GrpcGetChatRoomMember, {"Chatroom":"5977226699@chatroom"})
15:45:29 SILL DedupeApi dedupeApi(GrpcGetChatRoomMember) deduped api call with existing results.
15:45:29 SILL PadproManager syncRoomMember(5977226699@chatroom) total 4 members
15:45:29 VERB PadproManager getRoomMemberIdList(5977226699@chatroom) length=4
15:45:29 SILL PuppetPadpro roomMemberList() = 4
15:45:30 VERB Puppet roomMemberPayload(roomId=5977226699@chatroom, contactId=zhao_cq)
15:45:30 VERB PadproManager roomMemberRawPayload(5977226699@chatroom)
TypeError: Cannot read property 'bigHeadUrl' of undefined
    at PuppetPadpro.<anonymous> (/root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/puppet-padpro.js:897:36)
    at Generator.next (<anonymous>)
    at /root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/puppet-padpro.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/puppet-padpro.js:21:12)
    at PuppetPadpro.roomMemberRawPayloadParser (/root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/puppet-padpro.js:895:16)
    at PuppetPadpro.<anonymous> (/root/code/welinkwechatbot/node_modules/wechaty-puppet/dist/src/puppet.js:736:40)
    at Generator.next (<anonymous>)
    at fulfilled (/root/code/welinkwechatbot/node_modules/wechaty-puppet/dist/src/puppet.js:22:58)
```

**Comment by windmemory** [comment]
I just tested with `0.0.28` and can not reproduce the issue, could you please re-test this issue?

**Comment by windmemory** [comment]
Need more investigation on this issue.

**Comment by windmemory** [comment]
Should be fixed with `0.0.42`, please test this with that version @kis87988

**Comment by kis87988** [comment]
test and it works

**Comment by zhoumh1988** [comment]
It happened on version 0.0.36, I try to upgrade to 0.0.55.
@windmemory 
![image](https://user-images.githubusercontent.com/7434920/55301394-072cf280-546f-11e9-8b29-e81fc580e348.png)

**Comment by kis87988** [comment]
@zhoumh1988 does that mean it works @ version 0.0.55 or it doesn’t work @ version 0.0.55?

**Comment by zhoumh1988** [comment]
> @zhoumh1988 does that mean it works @ version 0.0.55 or it doesn’t work @ version 0.0.55?

I just deployed it. Run for a while to see.
