### ISSUE TITLE
Send File Error

### ISSUE THREAD

**Issue by lhr0909** [botorange/wechaty-puppet-padpro#34]
This file is sent via FileBox initialized by URL

```
00:34:29 VERB Contact say(FileBox#Url<1.Marijuana-Infused-Edible-Presentation-10-3-2018.pdf>)
00:34:29 VERB PuppetPadpro messageSendFile("{"contactId":"wxid_1602626028312"}", FileBox#Url<1.Marijuana-Infused-Edible-Presentation-10-3-2018.pdf>)
00:34:29 SILL PuppetPadpro fileType application/pdf
00:34:29 SILL CDNManager uploadFile(wxid_1602626028312, JVBERi0xLjYNJeLjz9MNCjMxNyAwIG9iag08PC9MaW5lYXJpemVkIDEvTCAyMzQyNjEvTyAzMTkvRSA4NDA3MS9OIDE2L1QgMjMz)
Error: CDNManager sendFile() failed, no CDN info yet, can not send file.
    at CDNManager.<anonymous> (/root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:53:23)
    at Generator.next (<anonymous>)
    at /root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:3:12)
    at CDNManager.uploadFile (/root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:50:16)
    at PuppetPadpro.<anonymous> (/root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/puppet-padpro.js:808:62)
    at Generator.next (<anonymous>)
    at fulfilled (/root/code/welinkwechatbot/node_modules/@xanthous/wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by lhr0909** [comment]
Tried it one more time after waiting for the bot to fully startup, got the following log, and the sent file cannot be downloaded.

![image](https://user-images.githubusercontent.com/1154575/50574626-07ddca80-0e27-11e9-9926-de16d47be873.png)


```
00:39:05 VERB Contact say(FileBox#Url<1.a0d04256df25654928b60d2a8619f4f7>)
00:39:05 VERB PuppetPadpro messageSendFile("{"contactId":"wxid_1602626028312"}", FileBox#Url<1.a0d04256df25654928b60d2a8619f4f7>)
00:39:05 SILL PuppetPadpro fileType .a0d04256df25654928b60d2a8619f4f7
00:39:05 SILL CDNManager uploadFile(wxid_1602626028312, QIcAAM7KC7EHAAEADQAAAFAAAABgABMAAQMAAKQ2AACkNgAAHQAAAIHJ60UAAAAAwsyopAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
00:39:05 SILL CDNManager sendCdnRequest(/uploadcheckmd5)
00:39:05 VERB CDNManager uploadFile() file 1.a0d04256df25654928b60d2a8619f4f7 not exists in cdn, upload it...
00:39:05 SILL CDNManager _uploadFile()
00:39:05 SILL CDNManager sendCdnRequest(/uploadv3)
00:39:05 SILL PadproGrpc GrpcSendApp(wxid_1602626028312)
00:39:05 SILL DedupeApi dedupe() no need to dedupe api GrpcSendApp.
00:39:05 SILL WechatGateway sendLong() reqSeq: 2225943146
00:39:05 SILL WechatGateway sendLong() receive back package size: 148
```

**Comment by windmemory** [comment]
Can you reproduce this issue? If so, please provide some more details, if not, let's close this issue for now :)
