### ISSUE TITLE
room-join 消息错误 no inviterId found

### ISSUE THREAD

**Issue by fatesinger** [botorange/wechaty-puppet-padpro#37]
邀请成员加入项目消息，有时会报错

```
nodejs.unhandledRejectionError: no inviterId found
    at PuppetPadpro.<anonymous> (/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:272:27)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58)
```
其他消息，有时也会报错

```
nodejs.unhandledRejectionError: no changerId found
    at PuppetPadpro.<anonymous> (/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:336:27)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58)
```

**Comment by windmemory** [comment]
有更详细一点的错误日志么？

**Comment by fatesinger** [comment]
只有这些，而且是偶现，同一个人邀请其他人加入群，有时候是好的，有时候会报错。

如果出现报错，再次邀请还是会报错。
先让群内其他人邀请一个人加入群，再次邀请就不会报错了。

**Comment by lhr0909** [comment]
建议打开 `BROLOG_LEVEL=silly` 再记录一下

**Comment by fatesinger** [comment]
no inviterId found 的日志

``` TypeScript
14:39:17 VERB PuppetPadpro roomMemberList(4717869347@chatroom)
14:39:17 VERB PadproManager getRoomMemberIdList(4717869347@chatroom)
14:39:17 VERB PadproManager getRoomMemberIdList(4717869347@chatroom) length=3
14:39:17 SILL PuppetPadpro roomMemberList() = 3
14:39:17 VERB Puppet contactSearch(query={"alias":"山下的朋友你们好"}, idList.length = 3)
14:39:17 SILL Puppet contactSearch() searchIdList.length = 3
14:39:17 VERB Puppet contactQueryFilterFactory({"alias":"山下的朋友你们好"})
14:39:17 SILL Puppet contactSearch() searchContactPayloadList.length = 0
14:39:17 VERB Puppet roomMemberPayload(roomId=4717869347@chatroom, contactId=wxid_uua6les58i3y22)
14:39:17 VERB Puppet roomMemberPayload(roomId=4717869347@chatroom, contactId=weobo_102205128)
14:39:17 VERB Puppet roomMemberPayload(roomId=4717869347@chatroom, contactId=wxid_zbmv092s1a0q12)
2019-01-04 14:39:17,725 ERROR 10944 nodejs.unhandledRejectionError: no inviterId found
    at PuppetPadpro.<anonymous> (/home/assistant/pro-teamin-community-services/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:273:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/assistant/pro-teamin-community-services/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58)
name: "unhandledRejectionError"
pid: 10944
hostname: iZ2ze2a5bjwun79j2je2tlZ

14:39:17 ERR Config ###########################
14:39:17 ERR Config unhandledRejection: unhandledRejectionError: no inviterId found [object Promise]
14:39:17 ERR Config ###########################
14:39:17 ERR Config process.on(unhandledRejection) promise.catch(no inviterId found)
Config { unhandledRejectionError: no inviterId found
    at PuppetPadpro.<anonymous> (/home/assistant/pro-teamin-community-services/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:273:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/assistant/pro-teamin-community-services/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58) name: 'unhandledRejectionError' }
(node:10944) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 13)
14:39:17 SILL GrpcGateway parse(GrpcGetContact) get response: [{"MsgType":2,"UserName":"4717869347@chatroom","NickName":"","Signature":"","SmallHeadImgUrl":"","BigHeadImgUrl":"http://wx.qlogo.cn/mmcrhead/naPHoFY2n5SDG7EloSDqerXs41ALgMM4S3c4uurX06waIburW5AhKZxAPa
14:39:17 SILL DedupeApi dedupeApi(GrpcGetContact) got results from external service, resolve 0 duplicate api calls.
14:39:17 SILL Puppet roomPayload(4717869347@chatroom) cache SET
14:39:17 VERB PuppetPadpro roomMemberList(4717869347@chatroom)
14:39:17 VERB PadproManager getRoomMemberIdList(4717869347@chatroom)
14:39:17 VERB PadproManager getRoomMemberIdList(4717869347@chatroom) length=3
14:39:17 SILL PuppetPadpro roomMemberList() = 3
14:39:17 SILL Contact ready() @ Puppet#0<PuppetPadpro>(padchat)/PuppetPadpro#0
14:39:17 SILL Contact ready() isReady() true
14:39:17 SILL Contact ready() @ Puppet#0<PuppetPadpro>(padchat)/PuppetPadpro#0
14:39:17 SILL Contact ready() isReady() true
14:39:17 SILL Contact ready() @ Puppet#0<PuppetPadpro>(padchat)/PuppetPadpro#0
14:39:17 SILL Contact ready() isReady() true
14:39:17 SILL Contact ready() @ Puppet#0<PuppetPadpro>(padchat)/PuppetPadpro#0
14:39:17 SILL Contact ready() isReady() true
14:39:17 SILL Contact ready() @ Puppet#0<PuppetPadpro>(padchat)/PuppetPadpro#0
14:39:17 SILL Contact ready() isReady() true
14:39:17 VERB Puppet selfId()
14:39:17 VERB Puppet selfId()
14:39:17 VERB Message mention()
14:39:17 VERB Message mention() text = "1", mentionNameList = "[]"
14:39:17 SILL Message message.mention() can not found member using room.member() from mentionList, metion string: []
14:39:17 VERB Puppet selfId()
14:39:17 VERB ContactSelf name()
14:39:17 VERB Message mention()
14:39:17 VERB Message mention() text = "1", mentionNameList = "[]"
14:39:17 SILL Message message.mention() can not found member using room.member() from mentionList, metion string: []
contactList []
14:39:17 VERB Room ready()

```

移除 bot  有时也会报错  no removerId found

详细日志

``` TypeScript
14:35:12 SILL PadproManager throttleQueue emit heartbeat.
14:35:12 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
14:35:12 SILL Wechaty memoryCheck() free: 1683 MB, require: 4 MB
14:35:12 SILL PadproManager syncMessage()
14:35:12 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
14:35:12 SILL WechatGateway sendLong() reqSeq: 2012270330
14:35:13 SILL WechatGateway sendLong() receive back package size: 390
14:35:13 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":[{"MsgId":1601504421,"FromUserName":"4400870633@chatroom","ToUserName":"wxid_uua6les58i3y22","MsgType":10000,"Content":"你被\"山下的朋友你们好\"移出群聊","Status":4,"ImgStatus":1,"ImgBuf":null,"CreateTime":
14:35:13 VERB PadproManager syncMessage() got 1 message(s).
14:35:13 VERB PuppetPadpro onPadproMessage({id=1601504421, type=Sys(10000)})
14:35:13 VERB PuppetPadpro onPadproMessageFriendshipEvent({id=1601504421})
14:35:13 VERB PuppetPadpro onPadproMessageRoomEventJoin({id=1601504421})
14:35:13 VERB PuppetPadpro onPadproMessageRoomEventLeave({id=1601504421})
14:35:13 SILL PuppetPadpro onPadproMessageRoomEventLeave() roomLeaveEvent="{"leaverNameList":[null],"removerName":"山下的朋友你们好","roomId":"4400870633@chatroom"}"
14:35:13 VERB Puppet roomMemberSearch(4400870633@chatroom, undefined)
14:35:13 VERB PuppetPadpro onPadproMessageRoomEventTopic({id=1601504421})
14:35:13 VERB Puppet roomMemberSearch(4400870633@chatroom, "山下的朋友你们好")
14:35:13 VERB Puppet roomMemberSearch(4400870633@chatroom, {"roomAlias":"山下的朋友你们好"})
14:35:13 VERB PuppetPadpro roomMemberList(4400870633@chatroom)
14:35:13 VERB PadproManager getRoomMemberIdList(4400870633@chatroom)
14:35:13 VERB PadproManager getRoomMemberIdList(4400870633@chatroom) length=3
14:35:13 SILL PuppetPadpro roomMemberList() = 3
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=wxid_zbmv092s1a0q12)
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=wxid_uua6les58i3y22)
14:35:13 VERB PadproManager roomMemberRawPayload(4400870633@chatroom)
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=weobo_102205128)
14:35:13 SILL Puppet roomMemberPayload(4400870633@chatroom) cache SET
14:35:13 VERB Puppet roomMemberSearch(4400870633@chatroom, {"name":"山下的朋友你们好"})
14:35:13 VERB PuppetPadpro roomMemberList(4400870633@chatroom)
14:35:13 VERB PadproManager getRoomMemberIdList(4400870633@chatroom)
14:35:13 VERB PadproManager getRoomMemberIdList(4400870633@chatroom) length=3
14:35:13 SILL PuppetPadpro roomMemberList() = 3
14:35:13 VERB Puppet contactSearch(query={"name":"山下的朋友你们好"}, idList.length = 3)
14:35:13 SILL Puppet contactSearch() searchIdList.length = 3
14:35:13 VERB Puppet contactQueryFilterFactory({"name":"山下的朋友你们好"})
14:35:13 SILL Puppet contactSearch() searchContactPayloadList.length = 0
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=wxid_zbmv092s1a0q12)
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=wxid_uua6les58i3y22)
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=weobo_102205128)
14:35:13 VERB Puppet roomMemberSearch(4400870633@chatroom, {"contactAlias":"山下的朋友你们好"})
14:35:13 VERB PuppetPadpro roomMemberList(4400870633@chatroom)
14:35:13 VERB PadproManager getRoomMemberIdList(4400870633@chatroom)
14:35:13 VERB PadproManager getRoomMemberIdList(4400870633@chatroom) length=3
14:35:13 SILL PuppetPadpro roomMemberList() = 3
14:35:13 VERB Puppet contactSearch(query={"alias":"山下的朋友你们好"}, idList.length = 3)
14:35:13 SILL Puppet contactSearch() searchIdList.length = 3
14:35:13 VERB Puppet contactQueryFilterFactory({"alias":"山下的朋友你们好"})
14:35:13 SILL Puppet contactSearch() searchContactPayloadList.length = 0
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=wxid_zbmv092s1a0q12)
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=wxid_uua6les58i3y22)
14:35:13 VERB Puppet roomMemberPayload(roomId=4400870633@chatroom, contactId=weobo_102205128)
2019-01-04 14:35:13,177 ERROR 10944 nodejs.unhandledRejectionError: no removerId found
    at PuppetPadpro.<anonymous> (/home/assistant/pro-teamin-community-services/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:303:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/assistant/pro-teamin-community-services/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58)
name: "unhandledRejectionError"
pid: 10944
hostname: iZ2ze2a5bjwun79j2je2tlZ

14:35:13 ERR Config ###########################
14:35:13 ERR Config unhandledRejection: unhandledRejectionError: no removerId found [object Promise]
14:35:13 ERR Config ###########################
14:35:13 ERR Config process.on(unhandledRejection) promise.catch(no removerId found)
Config { unhandledRejectionError: no removerId found
    at PuppetPadpro.<anonymous> (/home/assistant/pro-teamin-community-services/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:303:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/assistant/pro-teamin-community-services/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58) name: 'unhandledRejectionError' }
(node:10944) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 11)
14:35:13 SILL PadproManager syncMessage()
14:35:13 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
14:35:13 SILL WechatGateway sendLong() reqSeq: 3196395842
14:35:13 SILL WechatGateway sendLong() receive back package size: 582
14:35:13 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":[{"MsgType":2,"UserName":"4400870633@chatroom","NickName":"","Signature":"","SmallHeadImgUrl":"","BigHeadImgUrl":"http://wx.qlogo.cn/mmcrhead/PiajxSqBRaELC2N5Y5RrXaQeWJwM0karTrb5K6XWRvugSHoUXr
14:35:13 VERB PadproManager syncMessage() got 1 message(s).
14:35:13 VERB RoomConverter convertRoom() use alternative way to convert.
14:35:43 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
14:35:43 INFO PadproManager setContactAndRoomData() more than 3 minutes no change on data, emit ready event.
14:35:43 SILL Wechaty initPuppetEventBridge() puppet.on(ready)
2019-01-04 14:35:43,794 INFO 10944 padchat is ready
14:35:43 SILL StateSwitch <WechatyReady> on() is false
14:35:43 VERB StateSwitch <WechatyReady> on(true) <- (false)
14:35:43 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
14:35:43 SILL PadproManager debounceQueue heartbeat result: {}

14:35:43 SILL WechatGateway sendLong() reqSeq: 1542863067
14:35:43 SILL PadproManager throttleQueue emit heartbeat.
14:35:43 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
14:35:43 SILL Wechaty memoryCheck() free: 1682 MB, require: 4 MB
14:35:43 SILL WechatGateway sendLong() receive back package size: 20
14:35:43 SILL PadproManager syncMessage()
14:35:43 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
14:35:43 SILL WechatGateway sendLong() reqSeq: 2160325547
14:35:44 SILL WechatGateway sendLong() receive back package size: 230
14:35:44 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
14:35:44 VERB PadproManager syncMessage() got 0 message(s).
```

**Comment by windmemory** [comment]
调研了一下这个问题，主要导致的原因是备注的同步问题，设置备注之后，群事件的推送是推送了备注名，但备注没有被正确同步。

提交了fix，这个issue先关掉了，使用版本`v0.0.32`应该不会有这个问题了，如果持续存在，请reopen

**Comment by fatesinger** [comment]
还是会出现这个问题，已经升级到了 `v0.0.35` 版本，当前群报错后，再次邀请还是会报错。

**Comment by windmemory** [comment]
今天发现了代码里面一个可能导致这个问题的bug，在`v0.0.39`已经修复，请麻烦再用新版本试试看，是否还有这个问题 @fatesinger
