### ISSUE TITLE
 Bot自动注销并停止

### ISSUE THREAD

**Issue by pysingh09** [botorange/wechaty-puppet-padpro#43]
我从控制台复制了以下消息。

请帮助永远保持联系
Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/ubuntu/pro/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/ubuntu/pro/node_modules/mysql/lib/Connection.js:97:28)
    at Socket.<anonymous> (/home/ubuntu/pro/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:187:15)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by windmemory** [comment]
This is not related to `wechaty-puppet-padpro`, please check your mysql db.
