### ISSUE TITLE
Unknown jsonPayload error

### ISSUE THREAD

**Issue by osmanmesutozcan** [botorange/wechaty-puppet-padpro#45]
padpro version: `0.0.35`

We run wechay kubernetes on Tencent cloud using node ports so wechaty has a public ip. We have `PUBLIC_IP` override.

```
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
jsonPayload: { sysmsg:
   { '$': { type: 'multivoip' },
     multivoip:
      { notifydata:
         'CAQSHzE3MzYwMDA3NV8xNzA5NzgxNzA2XzE1NDcxOTUwODQYy/WnIyDkjJH31aPGnFwyGBgBqgYTNjIxMjIwNjc4MEBjaGF0cm9vbUIsCMva41IQy9rjUhgKIAAoATDMpeHhBaIGCGJpZW5pdXlpqgYIYmllbml1eWlCKwiwv7P7CBDL2uNSGAogACgCMMyl4eEFogYGa2F5aW1zqgYIYmllbml1eWlKGQgBEAAYACAAKAAwADgAQANIqApQAFgAYACoBrCfpaaFh5esWrAGyanh4QU=',
        needpush: '0',
        pushtype: '1' } } }
Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
jsonPayload: { sysmsg:
   { '$': { type: 'multivoip' },
     multivoip:
      { banner:
         'Ch8xNzM2MDAwNzVfMTcwOTc4MTcwNl8xNTQ3MTk1MDg0EMv1pyMY5IyR99WjxpxcKAIyEzYyMTIyMDY3ODBAY2hhdHJvb206Kwiwv7P7CBDL2uNSGAogACgCMMyl4eEFogYGa2F5aW1zqgYIYmllbml1eWlQl+6s4IMt',
        needpush: '0',
        pushtype: '1' } } }
Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
jsonPayload: { sysmsg:
   { '$': { type: 'multivoip' },
     multivoip:
      { banner:
         'Ch8xNzM2MDAwNzVfMTcwOTc4MTcwNl8xNTQ3MTk1MDg0EMv1pyMY5IyR99WjxpxcKAIyEzYyMTIyMDY3ODBAY2hhdHJvb206LAjL2uNSEMva41IYCiAAKAEwzKXh4QWiBghiaWVuaXV5aaoGCGJpZW5pdXlpOisIsL+z+wgQy9rjUhgKIAAoAjDMpeHhBaIGBmtheWltc6oGCGJpZW5pdXlpUOjprOCDLQ==',
        needpush: '0',
        pushtype: '1' } } }
jsonPayload: { sysmsg:
   { '$': { type: 'multivoip' },
     multivoip:
      { notifydata:
         'CAQSHzE3MzYwMDA3NV8xNzA5NzgxNzA2XzE1NDcxOTUwODQYy/WnIyDkjJH31aPGnFwyGBgBqgYTNjIxMjIwNjc4MEBjaGF0cm9vbUIrCLC/s/sIEMva41IYCiAAKAIwzKXh4QWiBgZrYXlpbXOqBghiaWVuaXV5aUoZCAEQABgAIAAoADAAOABAA0ioClAAWABgAKgGmNGopoWH16VtsAbKqeHhBQ==',
        needpush: '0',
        pushtype: '1' } } }
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
(node:43) UnhandledPromiseRejectionWarning: Error: unknown jsonPayload sysmsg type: multivoip
    at Object.<anonymous> (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:97:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/app/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/room-event-join-message-parser.js:4:58)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
2019-01-11T08:46:54.939Z wechatbot:provider Error: no payload
    at AnotherOriginalClass.<anonymous> (/opt/app/node_modules/wechaty/dist/src/user/contact.js:348:23)
    at Generator.next (<anonymous>)
    at /opt/app/node_modules/wechaty/dist/src/user/contact.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/app/node_modules/wechaty/dist/src/user/contact.js:3:12)
    at AnotherOriginalClass.alias (/opt/app/node_modules/wechaty/dist/src/user/contact.js:343:16)
    at contactPayload (/opt/app/dist/src/botadapter/wechatbot.listeners.provider.js:235:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-01-11T08:46:55.018Z wechatbot:minio object not found, creating
08:48:50 INFO WechatGateway sendShort() failed for error: Error: connect ETIMEDOUT 203.205.129.101:80, retry the api.
9:33:04 INFO WechatGateway sendShort() failed for error: sendShort receive unknown paolB�m�], retry the api.f300000000d942100d000000006f6c4218d86d00a70400000000 ~�����B
09:33:05 INFO PadproGrpc GrpcCheckQRCode()
09:33:05 ERR WechatGateway Error happened when call api: GrpcGetChatRoomMember, params: {"Chatroom":"320715685@chatroom"}
sendShort receive unknown package: [126] 7e0ffffffff300000000d942100d000000006f6c4218dolB�m�]0400000000 ~�����B
```

**Comment by osmanmesutozcan** [comment]
@lhr0909

**Comment by windmemory** [comment]
This is caused by voice call, currently wechaty can not handle voice call.

Close for now
