### ISSUE TITLE
同一个进程启动多个bot会出错

### ISSUE THREAD

**Issue by zhengzhejun** [botorange/wechaty-puppet-padpro#61]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：wechaty@0.22.6
- wechaty-puppet-padpro 版本：wechaty-puppet-padpro@0.0.41
- node 版本： (运行 `node --version` 获取版本) v11.8.0
- 你使用的操作系统：os x

## 2. Bug 描述
一个进程启动多个bot，或者其中某一个bot调用stop时，会报如下错误。
Error: CacheManager getContactCount() has no cache.
    at CacheManager.getContactCount (/Users/zhengzhejun/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/cache-manager.js:92:19)
    at PadproManager.setContactAndRoomData (/Users/zhengzhejun/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:73:48)
    at SafeSubscriber.debounceQueueSubscription.debounceQueue.subscribe [as _next] (/Users/zhengzhejun/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:59:18)
    at SafeSubscriber.__tryOrUnsub (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:145:22)
    at Subscriber._next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DebounceQueue.Subject.next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subject.js:60:25)
    at DebounceQueue.RxQueue.next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rx-queue/bundles/rx-queue.umd.js:64:39)
    at SafeSubscriber._next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rx-queue/bundles/rx-queue.umd.js:103:75)
    at SafeSubscriber.__tryOrUnsub (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:145:22)
    at Subscriber._next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DebounceSubscriber.Subscriber._next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:89:26)
    at DebounceSubscriber.emitValue (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/operators/debounce.js:85:36)
    at DebounceSubscriber.notifyNext (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/operators/debounce.js:69:14)
    at InnerSubscriber._next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/Subscriber.js:66:18)
    at AsyncAction.dispatch (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/observable/interval.js:23:16)
    at AsyncAction._execute (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/scheduler/AsyncAction.js:71:18)
    at AsyncAction.execute (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/scheduler/AsyncAction.js:59:26)
    at AsyncScheduler.flush (/Users/zhengzhejun/node_modules/wechaty/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:52:32)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)

## 3. 复现的步骤 (或者解决的步骤)
核心代码：
```
let list = ['**********', '***********']
for (var i = 0; i < list.length; i++) {
    const WECHATY_PUPPET_PADPRO_TOKEN = list[i]
    const puppet = 'wechaty-puppet-padpro' // 使用ipad 的方式接入。
    const puppetOptions = {
        token: WECHATY_PUPPET_PADPRO_TOKEN,
    }
    const bot = new Wechaty({
        puppet,
        puppetOptions,
    })
    bot.on('logout', (user) => {
            console.log(`${user.name()} logouted`)
            bot.stop()
        })
        .on('login', (user) => {
            console.log(`${user.name()} login`)
            bot.say('Wechaty login').catch(console.error)
        })
        .on('scan', (qrcode, status) => {
            const qrcodeImageUrl = [
                'https://api.qrserver.com/v1/create-qr-code/?data=',
                encodeURIComponent(qrcode),
            ].join('')
            console.log("i:" + i)
            console.log(`[${status}] ${qrcodeImageUrl}\nScan QR Code above to log in: `)
            qrTerm.generate(qrcode, { small: false })
        })
        .on('error', (e) => {
            console.error('Bot error:', e)
        })
        .on('message', (msg) => {

        })

    bot.start()
        .catch(async e => {
            console.error('Bot start() fail:', e)
            await bot.stop()
            process.exit(-1)
        })
}
```

## 4. 期待程序运行的结果
两个微信号操作几次扫码登录，下线操作以后会触发上述错误

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
目前`wechaty-puppet-padpro`对于单进程多实例的支持不是很健壮，单进程多实例在未来会更新完善，但是目前可能会有一些问题。现在如果需要运行多个bot，建议使用多进程多bot的模式

**Comment by windmemory** [comment]
I just updated the version to `v0.0.59`, please try this with `v0.0.59`

**Comment by windmemory** [comment]
Close this issue since no more comments in last 18 days.

**Comment by wanyaxing** [comment]
请教如何实现多进程多bot。

我也碰到同样的问题了。
