### ISSUE TITLE
创建room后，报错not ready

### ISSUE THREAD

**Issue by fsindustry** [botorange/wechaty-puppet-padpro#69]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.22.6
- wechaty-puppet-padpro 版本：0.0.50
- node 版本： (运行 `node --version` 获取版本) v11.3.0
- 你使用的操作系统：mac os

## 2. Bug 描述
创建room失败，报错not ready
创建room代码如下：
const room = await bot.Room.create(matchedContacts, 'group test');
log.info('roomMgr', 'a new room created: "%s"', room);
await room.topic('group created');
执行到第3行时报错：
(node:86811) UnhandledPromiseRejectionWarning: Error: not ready
    at AnotherOriginalClass.<anonymous> (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:598:23)
    at Generator.next (<anonymous>)
    at /Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.topic (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:594:16)

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**
例子:
- 第一步：
- 第二步：
- 。。。

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
Please try with code below.
```ts
const room = await bot.Room.create(matchedContacts, 'group test');
log.info('roomMgr', 'a new room created: "%s"', room);
await room.ready();
await room.topic('group created');
```

**Comment by fsindustry** [comment]
my code is like this, but still throw error：
const room = await roomMgr.createRoom(bot, ["xxx", "xxx", "xxx"]);
room.on('ready', roomMgr.ready(room));

// roomMgr.js
async function ready(room) {
    await room.topic('group created');
    await room.say('Hello World!');
}

**Comment by windmemory** [comment]
we need a full reproduce code to help, from that code you pasted, I don't know what happened and what you did.

**Comment by fsindustry** [comment]
// roomMgr.js
// 创建群聊
async function createRoom(bot, contacts) {

    log.info('roomMgr', 'createRoom("%s")', contacts);

    // 校验联系人，至少需要3个联系人
    if (contacts.length < 2) {
        log.error('roomMgr', 'create a new room need at least 3 contacts.');
        return;
    }

    try {

        // 逐个查找联系人
        const matchedContacts = [];
        for (let idx = 0; idx < contacts.length; idx++) {

            // 查找一个联系人
            const contact = await contactMgr.findContact(bot, contacts[idx]);
            if (!contact) {
                log.warn('roomMgr', 'could not find contact: "%s"', contacts[idx]);
                continue;
            }

            log.info('roomMgr', 'contact id : "%s"', contact.id);
            matchedContacts.push(contact);
        }

        // 如果符合要求的联系人少于3个，则给出提示并返回
        if (matchedContacts.length < 2) {
            log.error('roomMgr', 'create a new room need at least 3 contacts.');
            return;
        }

        // 创建群聊，并绑定事件
        const room = await bot.Room.create(matchedContacts, 'group test');
        log.info('roomMgr', 'a new room created: "%s"', room);

        return room;
    } catch (e) {
        log.error('roomMgr', 'createRoom() exception:', e.stack);
        throw e
    }
}

// 当群聊就绪时调用
async function ready(room) {
    await room.topic('group created');
    await room.say('Hello World!');
}

// 导出模块
module.exports = {
    createRoom: createRoom,
    ready: ready
};



// contactMgr.js
const {
    log,
} = require('wechaty');

// 创建群聊

// 根据昵称查找联系人信息
async function findContact(bot, contactName) {
    return bot.Contact.find({name: contactName})
}

// 导出模块
module.exports = {
    findContact: findContact
};


// bot.js

// 联系人和群信息同步就绪
async function onReady() {

    console.log(`bot is ready.`);
    const room = await roomMgr.createRoom(bot, ["xxx", "xxx", "xxx"]);
    if (!room) {
        console.error('create room failed')
    }

    room.on('ready', roomMgr.ready(room));

}

**Comment by fsindustry** [comment]
I've tried again with the code above，and throw error logs below：
19:18:32 WARN Room topic() room not ready
(node:88379) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at _addListener (events.js:200:11)
    at AnotherOriginalClass.addListener (events.js:259:10)
    at AnotherOriginalClass.on (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:469:15)
    at Wechaty.onReady (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/core/bot.js:67:10)
(node:88379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:88379) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:88379) UnhandledPromiseRejectionWarning: Error: not ready
    at AnotherOriginalClass.<anonymous> (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:598:23)
    at Generator.next (<anonymous>)
    at /Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:3:12)
    at AnotherOriginalClass.topic (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/dist/src/user/room.js:594:16)
    at Object.ready (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/core/roomMgr.js:53:16)
    at Wechaty.onReady (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/core/bot.js:67:30)
(node:88379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Contact<瀚海百川> logout
19:22:49 INFO CacheManager release()
(node:88379) UnhandledPromiseRejectionWarning: ReadError: Database is not open
    at maybeError (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/levelup/lib/levelup.js:288:32)
    at LevelUP.put (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/levelup/lib/levelup.js:179:7)
    at FlashStore.<anonymous> (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:174:63)
    at step (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:23:23)
    at Object.next (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:4:53)
    at /Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:80:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:66:16)
    at FlashStore.set (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:168:20)
    at FlashStoreSync.set (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/flash-store/bundles/flash-store.umd.js:866:47)
    at CacheManager.setRoom (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/cache-manager.js:111:34)
    at PadproManager.<anonymous> (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:412:43)
    at Generator.next (<anonymous>)
    at /Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:3:12)
    at messages.forEach (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:373:37)
    at Array.forEach (<anonymous>)
    at PadproManager.<anonymous> (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:373:22)
    at Generator.next (<anonymous>)
    at /Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:3:12)
    at PadproManager.processMessages (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:372:16)
    at PadproManager.<anonymous> (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:368:24)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/fuzhengxin/workspace/workspace_idea/duhuwai/duhuwai-bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:4:58)

**Comment by fsindustry** [comment]
It's seems that I called bot.Room.create(matchedContacts, 'group test')，and get return value normaly，but the room is not created in fact；So after I called root.topic，it return not ready error.

**Comment by windmemory** [comment]
Do a `room.sync()` after you created the room.

**Comment by fsindustry** [comment]
I've tried room.sync()，but it's seems useless. And I also met the error below：

![image](https://user-images.githubusercontent.com/12935987/53540630-40f99900-3b51-11e9-9a25-ab2a106bdd25.png)

**Comment by windmemory** [comment]
We are using exactly the same code to create room and work for us.

Please investigate in your side.

**Comment by fsindustry** [comment]
Is it maybe a problem of token? Or can you please get a example to me?

**Comment by windmemory** [comment]
```ts
bot.on('message', function (message) {
  if (message.text() === 'create') {
    const room = await bot.Room.create(message.from());
    await room.sync();
    await room.topic('group created');
    await room.say('Created');
  }
}
```

**Comment by windmemory** [comment]
Have you solve your problem? @fsindustry

**Comment by windmemory** [comment]
Close this issue since no response last 6 days.
