### ISSUE TITLE
centos 环境模块安装失败 (node-nosql-leveldb 404)

### ISSUE THREAD

**Issue by smxyzb** [botorange/wechaty-puppet-padpro#78]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。
出现类似问题：https://blog.chatie.io/wechaty-installation-in-windows-10/   但是在contos下
## 1. 提供你的包版本信息
- wechaty 版本：0.22.6
- wechaty-puppet-padpro 版本：0.0.51
- node 版本： v10.15.3

- 你使用的操作系统：centos 3.10.0-862.el7.x86_64

## 2. Bug 描述
安装 /nosql-leveldb-v3.0.1-node-v64-linux-x64.tar.gz 出现404，导致后续流程不动

## 3. 复现的步骤 (或者解决的步骤)
第一步：
使用 cnpm  install ，安装到wechaty-puppet-padchat 后出现问题

## 4. 期待程序运行的结果
能够顺利进行安装

## 5. 程序实际运行的结果
出现 获取 nosql-leveldb-v3.0.1-node-v64-linux-x64.tar.gz  404提示

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```

⠧ [2/19] Installing puppeteer@^1.12.2[pm2-intercom@1.0.0 › pm2@github:Unitech/pm2#development] install pm2 from git github:Unitech/pm2#development, may be ver y slow, please keep patience                                                                                                                                   ⠧ [10/19] Installing is-buffer@~1.1.1[pm2@3.3.1 › gkt@https://tgz.pm2.io/gkt-1.0.0.tgz] install gkt from remote https://tgz.pm2.io/gkt-1.0.0.tgz, may be very  slow, please keep patience                                                                                                                                     ⠴ [10/19] Installing uuid@^3.3.2[wechaty-puppet-padchat@0.18.2 › flash-store@0.7.1 › levelup@github:zixia/levelup] install levelup from git github:zixia/level up, may be very slow, please keep patience                                                                                                                     ⠙ [10/19] Installing @jimp/plugin-scale@^0.4.0platform unsupported nodemon@1.18.10 › chokidar@2.1.2 › fsevents@^1.2.7 Package require os(darwin) not compatibl e with your platform(linux)                                                                                                                                    [fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(linux)                                                  ✔ Installed 19 packages                                                                                                                                        ✔ Linked 662 latest versions                                                                                                                                   [1/5] scripts.install puppeteer@^1.12.2 run "node install.js", root: "/home/wechatyProgram/node_modules/_puppeteer@1.13.0@puppeteer"                           Downloading Chromium r637110 - 109.4 Mb [====================] 100% 0.0s                                                                                       Chromium downloaded to /home/wechatyProgram/node_modules/_puppeteer@1.13.0@puppeteer/.local-chromium/linux-637110                                              [1/5] scripts.install puppeteer@^1.12.2 finished in 50s                                                                                                        [2/5] scripts.postinstall wechaty-puppet-padpro@0.0.50 › fast-xml-parser@^3.12.12 run "node tasks/postinstall.js \|\| exit 0", root: "/home/wechatyProgram/node_ modules/_fast-xml-parser@3.12.14@fast-xml-parser"                                                                                                              [2/5] scripts.postinstall wechaty-puppet-padpro@0.0.50 › fast-xml-parser@^3.12.12 finished in 498ms                                                            [3/5] scripts.postinstall nodemon@^1.18.10 run "node bin/postinstall \|\| exit 0", root: "/home/wechatyProgram/node_modules/_nodemon@1.18.10@nodemon"            [3/5] scripts.postinstall nodemon@^1.18.10 finished in 135ms                                                                                                   [4/5] scripts.install wechaty-puppet-padchat@0.18.2 › flash-store@0.7.1 › nosql-leveldb@^3.0.1 run "prebuild-install \|\| node-gyp rebuild", root: "/home/wechat yProgram/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb"                                                                                                      prebuild-install http request GET https://github.com/snowyu/node-nosql-leveldb/releases/download/v3.0.1/nosql-leveldb-v3.0.1-node-v64-linux-x64.tar.gz         prebuild-install http 404 https://github.com/snowyu/node-nosql-leveldb/releases/download/v3.0.1/nosql-leveldb-v3.0.1-node-v64-linux-x64.tar.gz                 prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=linux)                                                 make: Entering directory `/home/wechatyProgram/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb/build'                                                            CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o                                                                                make: g++: Command not found                                                                                                                                   make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o] Error 127                                                                        make: Leaving directory `/home/wechatyProgram/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb/build'                                                           gyp ERR! build error                                                                                                                                           gyp ERR! stack Error: `make` failed with exit code: 2                                                                                                          gyp ERR! stack     at ChildProcess.onExit (/home/node/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:262:23)                                         gyp ERR! stack     at ChildProcess.emit (events.js:189:13)                                                                                                     gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)                                                                   gyp ERR! System Linux 3.10.0-862.el7.x86_64                                                                                                                    gyp ERR! command "/home/node/bin/node" "/home/node/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"                           gyp ERR! cwd /home/wechatyProgram/node_modules/_nosql-leveldb@3.0.1@nosql-leveldb                                                                              gyp ERR! node -v v10.15.3                                                                                                                                      gyp ERR! node-gyp -v v3.8.0                                                                                                                                    gyp ERR! not ok                                                                                                                                                [npminstall:runscript:error] wechaty-puppet-padchat@0.18.2 › flash-store@0.7.1 › nosql-leveldb@^3.0.1 scripts.install run "prebuild-install \|\| node-gyp rebuil d" error: Error: Run "sh -c prebuild-install \|\| node-gyp rebuild" error, exit code 1                                                                           ✖ Install fail! Error: post install error, please remove node_modules before retry!                                                                            Run "sh -c prebuild-install \|\| node-gyp rebuild" error, exit code 1                                                                                            Error: post install error, please remove node_modules before retry!                                                                                            Run "sh -c prebuild-install \|\| node-gyp rebuild" error, exit code 1                                                                                                at ChildProcess.proc.on.code (/home/node/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)                                                          at ChildProcess.emit (events.js:189:13)                                                                                                                        at maybeClose (internal/child_process.js:970:16)                                                                                                               at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)                                                                                   npminstall version: 3.20.2                                                                                                                                     npminstall args: /home/node/bin/node /home/node/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cn pmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org
--

```

</details>

## 7. 其他信息
看了下该出错模块的git仓库，确实没有该 nosql-leveldb-v3.0.1-node-v64-linux-x64.tar.gz 文件
https://github.com/snowyu/node-nosql-leveldb/releases/download/v3.0.1/

[bug]

**Comment by windmemory** [comment]
我在aws上面没找到3.10的镜像，只有一个`CentOS Linux release 7.6.1810 (Core) - kernel 3.10.0-957.5.1.el7.x86_64. `

我在这个镜像上面成功安装了wechaty-puppet-padpro

![image](https://user-images.githubusercontent.com/6801292/57467578-5c052980-72b5-11e9-9191-914038dab8ad.png)

我参考了如下几个地址
安装nodejs在centos上 https://linuxize.com/post/how-to-install-node-js-on-centos-7/
安装gcc `yum groupinstall 'Development Tool'`
安装gcc之后npm gyp build的时候出现的问题（并没有在`CentOS Linux release 7.6.1810 (Core) - kernel 3.10.0-957.5.1.el7.x86_64. `出现，而是在其他版本的centos里面出现了） https://blog.csdn.net/qq_26744901/article/details/82504079

我无法复现出你的问题，所以我也没办法提供解决方案，请自己在网上搜索相关内容解决
或者可以选择其他版本的linux系统来安装

这个issue就关闭了
