### ISSUE TITLE
接受好友请求报错：ERR WechatGateway Error happened when call api: GrpcAcceptFriend

### ISSUE THREAD

**Issue by fsindustry** [botorange/wechaty-puppet-padpro#94]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：
- wechaty-puppet-padpro 版本：
- node 版本： (运行 `node --version` 获取版本)
- 你使用的操作系统：

## 2. Bug 描述
接受好友请求时报错如下：
11:00:31 ERR WechatGateway Error happened when call api: GrpcAcceptFriend, params: {"Content":"","Encryptusername":"v1_db327925c4b60449390fb26048214c713f3260a8ac5f184e54c6d0a4aae5ddc6@stranger","Sence":3,"Ticket":"v2_b91f1775d8f62a55dd585d5c5df175c4550ed7219971e475c1f47963ed41a46f958bdeb2ee6ee29d1928d3cddaf9995cd657905351abcd6ab571598dda374503@stranger","Type":3}
{ Error: 1 CANCELLED: Received http2 header with status: 504
    at Object.exports.createStatusError (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 1,
  metadata:
   Metadata {
     _internal_repr: { 'grpc-status': [Array], 'grpc-message': [Array] } },
  details: 'Received http2 header with status: 504' }

## 3. 复现的步骤 (或者解决的步骤)
订阅friendship监听，当收到好友请求时，自动接受好友请求；
async function onFriendship(friendship) {
    try {
        console.log(`received friend event.`)
        switch (friendship.type()) {

            // 1. New Friend Request

            case Friendship.Type.Receive:
                await friendship.accept();
                const contact = friendship.contact();

                console.log('friend accept: ', contact.name());
                contact.say('你好呀！' + contact.name());

                // 重新加载好友数据
                contact.sync();
                break

            // 2. Friend Ship Confirmed

            case Friendship.Type.Confirm:
                console.log(`friend ship confirmed`)
                break
        }
    } catch (e) {
        console.error(e)
    }
}

## 4. 期待程序运行的结果
自动接受好友请求，成功添加好友；

## 5. 程序实际运行的结果
运行报错，无法自动接受好友请求：ERR WechatGateway Error happened when call api: GrpcAcceptFriend

## 6. 完整的日志信息：
11:00:31 ERR WechatGateway Error happened when call api: GrpcAcceptFriend, params: {"Content":"","Encryptusername":"v1_db327925c4b60449390fb26048214c713f3260a8ac5f184e54c6d0a4aae5ddc6@stranger","Sence":3,"Ticket":"v2_b91f1775d8f62a55dd585d5c5df175c4550ed7219971e475c1f47963ed41a46f958bdeb2ee6ee29d1928d3cddaf9995cd657905351abcd6ab571598dda374503@stranger","Type":3}
{ Error: 1 CANCELLED: Received http2 header with status: 504
    at Object.exports.createStatusError (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/duhuwai/app/duhuwai-bot/node_modules/wechaty/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 1,
  metadata:
   Metadata {
     _internal_repr: { 'grpc-status': [Array], 'grpc-message': [Array] } },
  details: 'Received http2 header with status: 504' }

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
请使用最新版padpro再试一下是否可以复现

**Comment by windmemory** [comment]
因为最近六天没有回复，先关闭这issue，如果问题持续发生，请reopen这个issue
