### ISSUE TITLE
凌晨一点左右容易掉线

### ISSUE THREAD

**Issue by samstar** [botorange/wechaty-puppet-padpro#99]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：v0.22.6
- wechaty-puppet-padpro 版本：v0.0.53
- node 版本： (运行 `node --version` 获取版本) v10.15.1
- 你使用的操作系统：CentOS7

## 2. Bug 描述
凌晨一点左右容易掉线  WechatGateway initLongSocket() error

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
- 第一步：
- 第二步：
- 。。。

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
01:02:35 ERR WechatGateway initLongSocket() error happened with long host server connection: Error: read ETIMEDOUT
Error: no inviterId found
    at PuppetPadpro.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/puppet-padpro.js:273:27)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58)
01:03:57 WARN PadproManager releaseQueue() subscriptions have been released.
01:03:57 WARN PadproManager releaseQueue() queues have been released.
01:03:57 WARN CacheManager init() CacheManager not exist, no need to release it.
01:17:38 ERR WechatGateway initLongSocket() error happened with long host server connection: Error: read ETIMEDOUT
09:29:50 WARN sendShort receive unknown package: [126] 7e0ffffffff300000000df42080d704482eaa83adf2cc5b6008b0100000pD��:�,Ŷ�]
09:29:50 ERR WechatGateway Error happened when call api: GrpcNewInit, params: undefined
UNKNOWN_PACKAGE
TypeError: Cannot read property 'forEach' of null
    at PadproManager.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:373:22)
    at Generator.next (<anonymous>)
    at /root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:3:12)
    at PadproManager.processMessages (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:372:16)
    at PadproManager.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:117:24)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
09:29:50 ERR Wechaty start() exception: Cannot read property 'forEach' of null
TypeError: Cannot read property 'forEach' of null
    at PadproManager.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:373:22)
    at Generator.next (<anonymous>)
    at /root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:3:12)
    at PadproManager.processMessages (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:372:16)
    at PadproManager.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:117:24)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
14:28:46 WARN sendShort receive unknown package: [126] 7e0ffffffff3000000001e42080d494e1c1c6e1f575ec5f1008b0100000INnW^���]
14:28:46 ERR WechatGateway Error happened when call api: GrpcNewInit, params: undefined
UNKNOWN_PACKAGE
TypeError: Cannot read property 'forEach' of null
    at PadproManager.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:373:22)
    at Generator.next (<anonymous>)
    at /root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:3:12)
    at PadproManager.processMessages (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:372:16)
    at PadproManager.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:117:24)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
14:28:46 ERR Wechaty start() exception: Cannot read property 'forEach' of null
TypeError: Cannot read property 'forEach' of null
    at PadproManager.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:373:22)
    at Generator.next (<anonymous>)
    at /root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:3:12)
    at PadproManager.processMessages (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:372:16)
    at PadproManager.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:117:24)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: no inviterId found
    at PuppetPadpro.<anonymous> (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/puppet-padpro.js:273:27)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechat/wechaty-demo1/node_modules/_wechaty-puppet-padpro@0.0.53@wechaty-puppet-padpro/dist/src/puppet-padpro.js:22:58)
16:37:10 WARN PuppetPadpro onPadproMessageRoomEvent({id=roomMemberSearch() not found}) roomJoin retry() fail: undefined
19:01:13 WARN PuppetPadpro onPadproMessageRoomEvent({id=roomMemberSearch() not found}) roomJoin retry() fail: undefined
00:59:41 WARN PadproManager releaseQueue() subscriptions have been released.
00:59:41 WARN PadproManager releaseQueue() queues have been released.
00:59:41 WARN CacheManager init() CacheManager not exist, no need to release it.
01:12:24 ERR WechatGateway initLongSocket() error happened with long host server connection: Error: read ETIMEDOUT
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
请使用`PADPRO_LOG=silly`运行代码，然后提供一下断线的时候详细的错误log

**Comment by samstar** [comment]
> 请使用`PADPRO_LOG=silly`运行代码，然后提供一下断线的时候详细的错误log

00:51:28 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
00:51:28 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3012 times, booted 98624.97 seconds since boot.
00:51:28 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
00:51:28 SILL PadproManager debounceQueue heartbeat result: {}
00:51:29 SILL WechatGateway sendLong() reqSeq: 3146122515
00:54:58 VERB PuppetPadpro stop()
00:54:58 VERB PuppetPadpro logout()
00:54:58 VERB PadproManager logout()
00:54:58 VERB PadproManager stopInitData()
00:54:58 INFO CacheManager release()
00:54:58 VERB CacheManager releaseCache()
00:54:58 SILL CacheManager releaseCache() closing caches ...
00:54:58 SILL CacheManager releaseCache() cache closed.
00:54:58 VERB PadproManager stop()
00:54:58 VERB PadproManager stopCheckScan()
00:54:58 VERB PadproManager stopInitData()
00:54:58 VERB PadproGrpc stop()
00:54:58 INFO CacheManager release()
00:54:58 INFO WechatGateway stop()
01:07:39 INFO WechatGateway initLongSocket() connection to wechat long host server: 163.177.81.141 closed.
01:07:39 VERB WechatGateway cleanLongSocket() socket doesn't exist, no need to clean it.

**Comment by windmemory** [comment]
从提供的日志看，只能判断出可能是手动调用了`wechaty.stop()`停止了bot。

如果没有自己手动调用的话，请提供前面更多的log

**Comment by samstar** [comment]
> 从提供的日志看，只能判断出可能是手动调用了`wechaty.stop()`停止了bot。
> 
> 如果没有自己手动调用的话，请提供前面更多的log

00:47:56 VERB PadproManager syncMessage() got 0 message(s).
00:48:26 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
00:48:26 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3006 times, booted 98443.307 seconds since boot.
00:48:26 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
00:48:26 SILL PadproManager debounceQueue heartbeat result: {}
00:48:26 SILL WechatGateway sendLong() reqSeq: 1090639926
00:48:26 SILL PadproManager throttleQueue emit heartbeat.
00:48:26 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
00:48:26 SILL WechatGateway sendLong() receive back package size: 20
00:48:26 SILL PadproManager syncMessage()
00:48:26 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
00:48:26 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 3533 times, booted 98443.476 seconds since boot.
00:48:26 SILL WechatGateway sendLong() reqSeq: 4122764294
00:48:26 SILL WechatGateway sendLong() receive back package size: 246
00:48:26 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
00:48:26 VERB PadproManager syncMessage() got 0 message(s).
00:48:56 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
00:48:56 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3007 times, booted 98473.609 seconds since boot.
00:48:56 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
00:48:56 SILL PadproManager debounceQueue heartbeat result: {}
00:48:56 SILL WechatGateway sendLong() reqSeq: 323331892
00:48:57 SILL PadproManager throttleQueue emit heartbeat.
00:48:57 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
00:48:57 SILL WechatGateway sendLong() receive back package size: 20
00:48:57 SILL PadproManager syncMessage()
00:48:57 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
00:48:57 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 3534 times, booted 98473.737 seconds since boot.
00:48:57 SILL WechatGateway sendLong() reqSeq: 686289452
00:48:57 SILL WechatGateway sendLong() receive back package size: 246
00:48:57 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
00:48:57 VERB PadproManager syncMessage() got 0 message(s).
00:49:27 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
00:49:27 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3008 times, booted 98503.876 seconds since boot.
00:49:27 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
00:49:27 SILL PadproManager debounceQueue heartbeat result: {}
00:49:27 SILL WechatGateway sendLong() reqSeq: 821446466
00:49:27 SILL PadproManager throttleQueue emit heartbeat.
00:49:27 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
00:49:27 SILL WechatGateway sendLong() receive back package size: 20
00:49:27 SILL PadproManager syncMessage()
00:49:27 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
00:49:27 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 3535 times, booted 98504.012 seconds since boot.
00:49:27 SILL WechatGateway sendLong() reqSeq: 3426285968
00:49:27 SILL WechatGateway sendLong() receive back package size: 246
00:49:27 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
00:49:27 VERB PadproManager syncMessage() got 0 message(s).
00:49:57 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
00:49:57 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3009 times, booted 98534.151 seconds since boot.
00:49:57 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
00:49:57 SILL PadproManager debounceQueue heartbeat result: {}
00:49:57 SILL WechatGateway sendLong() reqSeq: 3020373504
00:49:57 SILL PadproManager throttleQueue emit heartbeat.
00:49:57 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
00:49:57 SILL WechatGateway sendLong() receive back package size: 20
00:49:57 SILL PadproManager syncMessage()
00:49:57 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
00:49:57 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 3536 times, booted 98534.282 seconds since boot.
00:49:57 SILL WechatGateway sendLong() reqSeq: 368808017
00:49:57 SILL WechatGateway sendLong() receive back package size: 246
00:49:57 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
00:49:57 VERB PadproManager syncMessage() got 0 message(s).
00:50:27 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
00:50:27 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3010 times, booted 98564.418 seconds since boot.
00:50:27 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
00:50:27 SILL PadproManager debounceQueue heartbeat result: {}
00:50:27 SILL WechatGateway sendLong() reqSeq: 2761358760
00:50:27 SILL PadproManager throttleQueue emit heartbeat.
00:50:27 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
00:50:27 SILL WechatGateway sendLong() receive back package size: 20
00:50:27 SILL PadproManager syncMessage()
00:50:27 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
00:50:27 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 3537 times, booted 98564.543 seconds since boot.
00:50:27 SILL WechatGateway sendLong() reqSeq: 263074029
00:50:27 SILL WechatGateway sendLong() receive back package size: 246
00:50:28 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
00:50:28 VERB PadproManager syncMessage() got 0 message(s).
00:50:57 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
00:50:57 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3011 times, booted 98594.686 seconds since boot.
00:50:57 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
00:50:57 SILL PadproManager debounceQueue heartbeat result: {}
00:50:58 SILL WechatGateway sendLong() reqSeq: 399429890
00:50:58 SILL PadproManager throttleQueue emit heartbeat.
00:50:58 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
00:50:58 SILL WechatGateway sendLong() receive back package size: 20
00:50:58 SILL PadproManager syncMessage()
00:50:58 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
00:50:58 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 3538 times, booted 98594.838 seconds since boot.
00:50:58 SILL WechatGateway sendLong() reqSeq: 3520814172
00:50:58 SILL WechatGateway sendLong() receive back package size: 246
00:50:58 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
00:50:58 VERB PadproManager syncMessage() got 0 message(s).
00:51:28 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
00:51:28 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3012 times, booted 98624.97 seconds since boot.
00:51:28 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
00:51:28 SILL PadproManager debounceQueue heartbeat result: {}
00:51:29 SILL WechatGateway sendLong() reqSeq: 3146122515
00:54:58 VERB PuppetPadpro stop()
00:54:58 VERB PuppetPadpro logout()
00:54:58 VERB PadproManager logout()
00:54:58 VERB PadproManager stopInitData()
00:54:58 INFO CacheManager release()

**Comment by windmemory** [comment]
从上面的日志看，连接一直是正常的状态，没有因为连接问题而重置或者断线，所以请检查代码，是否在某些地方调用了`wechaty.stop()`函数，或者可能是`bot.stop()`之类的

如果因为监听到某些`error`而执行了`stop()`，请打印error，这样才能知道问题出在哪

**Comment by samstar** [comment]
> 从上面的日志看，连接一直是正常的状态，没有因为连接问题而重置或者断线，所以请检查代码，是否在某些地方调用了`wechaty.stop()`函数，或者可能是`bot.stop()`之类的
> 
> 如果因为监听到某些`error`而执行了`stop()`，请打印error，这样才能知道问题出在哪

经检查，代码里面没有调用过`stop`方法。。`error`处理也仅仅是打印了日志

**Comment by windmemory** [comment]
请问中间有没有网络中断的情况，这个代码是在什么地方运行的？是云端服务器么？

**Comment by windmemory** [comment]
Please try with `v0.0.59` and see if this issue still happens.

**Comment by windmemory** [comment]
Close this issue since no more comments for last 18 days.
